# Default paths to external tools
# DO NOT EDIT THIS FILE, create a new file config.mk instead and 
# put your modifications there

# Root directory, do not modify
RCMC_ROOT=$(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# ARM compiler
CC_ARM=arm-none-eabi-gcc

# RISC-V compiler with ISA rv64imafd (MacSim)
CC_RV64IMAFD=$(RCMC_ROOT)tools/rv64imafd/bin/riscv64-unknown-elf-gcc
#CC_RV64IMAFD=riscv64-unknown-elf-gcc

# RISC-V compiler with ISA rv64i (FPGA)
CC_RV64I=$(RCMC_ROOT)tools/rv64i/bin/riscv64-unknown-elf-gcc

# GHDL
GHDL=$(RCMC_ROOT)tools/ghdl/bin/ghdl

# Include config.mk for user defined settings
-include $(RCMC_ROOT)config.mk