#!/bin/sh
# Compare the execution of one benchmark with MacSim and GHDL


# ------------------------------
# additional configuration
# ------------------------------

MEMORY_SIZE=131072
# TODO: ghdl crashes with larger memory

ROUTER="UBGG00"

CORNERBUF=8
# size of the corner buffer

FLAGS="--ieee=synopsys"
# FIXME: flags here and in ghdl_analyze.sh, generated by config.sh must be the same

# ------------------------------








# use pwd to get absolute paths
MYDIR=$(dirname $0)
GHDL="$(pwd)/${MYDIR}/../../tools/ghdl/bin/ghdl"
MACSIM="$(pwd)/${MYDIR}/../../macsim/build/macsim-seq"

# Color for messages.
COL_MSG='\033[1;30m'
COL_SUCCESS='\033[0;32m'
COL_FAIL='\033[0;31m'
COL_NONE='\033[0m'



if [ $# -ne 4 ]
then
    echo "Usage: $0 <core name> <noc width> <work directory> <RISC-V ELF file>"
    echo "Memory size, router configuration and corner buffer size can only be changed in the script"
    exit 1
fi

COREDIR=$(pwd)/${MYDIR}/../../fpga/$1
if [ ! -e "${COREDIR}" ]
then
    echo -e "core name not found!" 1>&2
    exit 2
fi
WIDTH="$2"
WORKDIR="$3"
mkdir -p ${WORKDIR}
ELF="$(pwd)/$4"
if [ ! -e "${ELF}" ]
then
    echo -e "ELF file not found!" 1>&2
    exit 3
fi

cd ${WORKDIR}
rm -f *.cf
TIME_START=$(date +%s)



# MacSim
printf "MacSim simulation"
${MACSIM} -A riscv -N${WIDTH}x${WIDTH} -J${CORNERBUF} -RP${ROUTER} -a ${ELF} -y macsim.regdump -q 1> macsim.log
MACSIM_CYCLES=$(grep "Execution Time" macsim.log | awk '{ print $3 }')
TIME_MACSIM=$(date +%s)
echo "${COL_MSG} ($((TIME_MACSIM-TIME_START)) seconds)${COL_NONE} simulated time: ${COL_MSG}${MACSIM_CYCLES} cycles${COL_NONE}"


# GHDL analysis
printf "GHDL analysis"
${COREDIR}/config.sh ${WIDTH} ${ROUTER} ${CORNERBUF} ${MEMORY_SIZE} ${ELF}
./ghdl_analyze.sh
${GHDL} -e ${FLAGS} NoC


# run GHDL simulation
TIME_ANALYSIS=$(date +%s)
echo "${COL_MSG} ($((TIME_ANALYSIS-TIME_MACSIM)) seconds)${COL_NONE}"
printf "GHDL simulation"
${GHDL} -r ${FLAGS} NoC --stop-time=$(($MACSIM_CYCLES+9))ns --vcd=ghdl.vcd 2> ghdl.log
cd ..


# convert to register dump
TIME_SIM=$(date +%s)
printf "${COL_MSG} ($((TIME_SIM-TIME_ANALYSIS)) seconds = "
echo "$(( MACSIM_CYCLES / (TIME_SIM-TIME_ANALYSIS) )) cycles/second)${COL_NONE}"

printf "Converting VCD to regdump"
awk -f vcd2regdump.awk ${WORKDIR}/ghdl.vcd > ${WORKDIR}/ghdl.regdump
TIME_CONV=$(date +%s)
echo "${COL_MSG} ($((TIME_CONV-TIME_SIM)) seconds)${COL_NONE}"


# comparison
if cmp --silent ${WORKDIR}/macsim.regdump ${WORKDIR}/ghdl.regdump
then
  echo "${COL_SUCCESS}Register dumps are equal!${COL_NONE}"
  exit 0
else
  echo "${COL_FAIL}Register dumps DIFFER!${COL_NONE}"
  exit 1
fi

