#OS
set(CMAKE_SYSTEM_NAME Generic)

## Cross-Compiler
set(RCMC_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../)
set(CROSS_COMPILER_PREFIX ${RCMC_ROOT_DIR}/tools/rv64i/bin/riscv64-unknown-elf-)

## Compiler
SET(CMAKE_C_COMPILER ${CROSS_COMPILER_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_COMPILER_PREFIX}g++)
SET(CMAKE_ASM_COMPILER ${CROSS_COMPILER_PREFIX}as)
SET(CMAKE_LINKER ${CROSS_COMPILER_PREFIX}ld)
set(CMAKE_OBJCOPY ${CROSS_COMPILER_PREFIX}objcopy)

set(TARGET_ARCH "-march=rv64i")
set(TARGET_BUILD_OPTIONS "-O3 -nostartfiles -ffreestanding -lc -lm -lgcc")
